### ISSUE TITLE
Check if MQTT broker is available before establishing connection

### ISSUE THREAD

**Issue by dusanb94** [mainflux/mproxy#27]
Before establishing a TCP connection with the MQTT broker, mProxy should issue a health check request to the broker. The broker might be up and running, but not ready to establish a connection yet due to the internal cluster synchronization, DB initialization, or any other reason. In that case, mProxy can establish a TCP connection with the broker that's not ready and end up dropping that connection later on when message exchange starts.

**Comment by drasko** [comment]
Resolved by https://github.com/mainflux/mainflux/pull/1305
